import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="overflow-x-hidden  font-body font-bold text-light-cyan bg-dark-blue">
      <Head>
        <title>RAG App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <main>
        <div className="py-64 mx-4 min-h-screen">
          <div className="container mx-auto bg-dark-grayish-blue rounded-lg lg:w-1/3">
            <div className="relative py-6 ">
              <div className="absolute  inset-x-1/4  w-auto top-5 ">
                <h2 className=" text-center text-neon-green text-xs font-medium tracking-wider">
                  ADVICE #117
                </h2>
              </div>

              <p className="mt-10 px-4 text-2xl text-center">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Possimus, vero.
              </p>
            </div>

            <div className=" inline-flex w-full mb-12 px-5  ">
              <img
                className="m-auto"
                src="/pattern-divider-desktop.svg"
                alt="divider"
              />
            </div>
          </div>
          <div className="container mx-auto relative -top-5 bg-neon-green rounded-full p-5 w-16">
            <img className="float-center" src="/icon-dice.svg" alt="play" />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
